server:
    port: 8002
spring:
    application:
        name: mango-backup
mango:
  backup: 
    datasource: 
      host: localhost
      userName: root
      password: root123
      database: mongo    
      
